### ISSUE TITLE
[Back-end] - CRUD notificações

### ISSUE THREAD

**Issue by oliveirabalsa** [Mentor-Cycle/mentor-cycle-be#27]
Precisamos de um CRUD de notificações.

![Image](https://github.com/Mentor-Cycle/mentor-cycle-be/assets/57500163/7e04b1ea-13e2-45bf-bf5a-0d14f071b8c5)

Baseado no figma, precisamos de alguns campos como:

id - uuid
title - string
description - string
image_url - string
read - boolean
created_at - Date
updated_at - Date
**Relacionamento - MUITOS PARA MUITOS, um usuário pode ter várias notificações e uma notificação pode ter vários usuários(em casos de notificações globais)**

**Comment by diegosano** [comment]
@oliveirabalsa posso ficar responsável por essa task?

**Comment by oliveirabalsa** [comment]
> @oliveirabalsa posso ficar responsável por essa task?

Com certeza!

**Comment by diegosano** [comment]
Vlw, vou começar a codar essa task então! 

Obs.: não consigo dar assign para mim e nem mover para "Em progresso"

**Comment by oliveirabalsa** [comment]
Fechou, vc já tem o .env?

**Comment by oliveirabalsa** [comment]
Estamos vendo a questão dos acessos

**Comment by diegosano** [comment]
Não tenho ainda

**Comment by iannak** [comment]
#43
