### ISSUE TITLE
[Back-end] - Enviar notificação

### ISSUE THREAD

**Issue by oliveirabalsa** [Mentor-Cycle/mentor-cycle-be#28]
**Bloqueada por https://github.com/orgs/Mentor-Cycle/projects/1/views/1?pane=issue&itemId=29756894**

Ao finalizar o CRUD de notificação devemos começar a implementar as notificações. Aqui então os cenários:

- Agendamento/Cancelamento de mentoria
- Completou perfil.

Ou seja, ao agendar uma mentoria, ou cancelar, deverá ser enviada uma notificação. Você irá entrar na função que faz isso dentro do código e adicionar mais uma linha após o agendamento/cancelamento que irá chamar a notificationService(ou algo do tipo) e criará a notificação.

**Comment by diegosano** [comment]
@oliveirabalsa fiquei com dúvida no cenário do usuário ter completado o perfil, para quem iremos enviar notificação? Também quando que é dado que o perfil foi completo no sign up mesmo?

**Comment by oliveirabalsa** [comment]
@diegosano para o próprio usuário que completou o perfil, isso deve ficar no update user e no signup. Se todos os campos estiverem preenchidos, esse usuário que foi criado/atualizado irá ter uma notificação de "perfil completo" e se o perfil dele tiver incompleto deverá receber uma notificação de completar perfil

**Comment by oliveirabalsa** [comment]
E no caso de mentorias serão notificados o usuário mentor e usuário mentorado
